import java.sql.Connection;
import java.sql.Statement;
import java.sql.Date;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Tharindu
 */
public class Medicine extends javax.swing.JFrame {
            Connection con = null;
            Statement stmt= null;
            ResultSet Rs = null;
    /**
     * Creates new form Medicine
     */
    public Medicine() {
        initComponents();
        con = databaseConnection.connection();
        SelectMed();
        GetCompany();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void SelectMed()
    {
        try
        {
            con = databaseConnection.connection();
            stmt = con.createStatement();
            Rs = stmt.executeQuery("SELECT * FROM medicine");
            MedicineTable.setModel(DbUtils.resultSetToTableModel(Rs));
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        MediID = new javax.swing.JLabel();
        MediName = new javax.swing.JLabel();
        MediPrice = new javax.swing.JLabel();
        MediExpDate = new javax.swing.JLabel();
        MediCom = new javax.swing.JLabel();
        ManfDate = new javax.swing.JLabel();
        MID = new javax.swing.JTextField();
        MName = new javax.swing.JTextField();
        MPrice = new javax.swing.JTextField();
        MCompany = new javax.swing.JComboBox<>();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MedicineTable = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        MQuantity = new javax.swing.JTextField();
        MediQuantity = new javax.swing.JLabel();
        MfDate = new com.toedter.calendar.JDateChooser();
        ExDate = new com.toedter.calendar.JDateChooser();
        companylbl = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Agentlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 255, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 153));
        jLabel2.setText("MANAGE MEDICINE");
        jLabel2.setToolTipText("");

        MediID.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        MediID.setText("Med ID");
        MediID.setToolTipText("");

        MediName.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        MediName.setText("Medicine Name");

        MediPrice.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        MediPrice.setText("Price");
        MediPrice.setToolTipText("");

        MediExpDate.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        MediExpDate.setText("Exp Date");
        MediExpDate.setToolTipText("");

        MediCom.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        MediCom.setText("Company");
        MediCom.setToolTipText("");

        ManfDate.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        ManfDate.setText("Man Date");
        ManfDate.setToolTipText("");

        MCompany.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N

        add.setBackground(new java.awt.Color(0, 255, 0));
        add.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(0, 255, 0));
        update.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        update.setText("UPDATE");
        update.setToolTipText("");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(0, 255, 0));
        delete.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        delete.setText("DELETE");
        delete.setToolTipText("");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        MedicineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "MediName", "Price", "Quantity", "Manufacture Date", "ExpDate", "Company"
            }
        ));
        MedicineTable.setSelectionBackground(new java.awt.Color(0, 255, 135));
        MedicineTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MedicineTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(MedicineTable);

        jLabel12.setFont(new java.awt.Font("Segoe UI Symbol", 1, 15)); // NOI18N
        jLabel12.setText("Medicine List");
        jLabel12.setToolTipText("");

        clear.setBackground(new java.awt.Color(0, 255, 0));
        clear.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        clear.setText("CLEAR");
        clear.setToolTipText("");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        MediQuantity.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        MediQuantity.setText("Quantity");
        MediQuantity.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MediID)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MediPrice)
                                    .addComponent(MediName)
                                    .addComponent(MediQuantity))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MName, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MID, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MediExpDate)
                            .addComponent(MediCom)
                            .addComponent(ManfDate))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ExDate, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MfDate, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(update)
                .addGap(18, 18, 18)
                .addComponent(delete)
                .addGap(18, 18, 18)
                .addComponent(clear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(424, 424, 424))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MfDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MediID)
                        .addComponent(ManfDate)
                        .addComponent(MID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ExDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MediName)
                        .addComponent(MediExpDate)
                        .addComponent(MName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MediPrice)
                    .addComponent(MediCom)
                    .addComponent(MCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MediQuantity))
                .addGap(81, 81, 81)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        companylbl.setFont(new java.awt.Font("Times New Roman Cyr", 1, 36)); // NOI18N
        companylbl.setText("COMPANY");
        companylbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                companylblMouseClicked(evt);
            }
        });

        Agentlbl.setFont(new java.awt.Font("Times New Roman Cyr", 1, 36)); // NOI18N
        Agentlbl.setText("AGENTS");
        Agentlbl.setToolTipText("");
        Agentlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgentlblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Agentlbl)
                    .addComponent(companylbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(208, 208, 208)
                                .addComponent(jLabel9))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(companylbl)
                                .addGap(18, 18, 18)
                                .addComponent(Agentlbl)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void GetCompany()
{
    try
    {
        con = databaseConnection.connection();
        stmt = con.createStatement();
        String query = "SELECT * FROM company";
        Rs = stmt.executeQuery(query);
        while(Rs.next())
        {
            String Mycomp = Rs.getString("comName");
            MCompany.addItem(Mycomp);
        }
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(null, "Invalid");
    }
}
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        try
        {
            java.sql.Date ManDate = new java.sql.Date(MfDate.getDate().getTime());
            java.sql.Date ExpDate = new java.sql.Date(ExDate.getDate().getTime());
            String query = "INSERT INTO medicine(MedicineID ,MedicineName,Price,Quantity,MfDate,ExpDate,MedCom) VALUES(?,?,?,?,?,?,?)";
            
            stmt = con.createStatement();
            
            PreparedStatement praparedStmt = con.prepareStatement(query);
            
            praparedStmt.setInt(1, Integer.valueOf(MID.getText()));
            praparedStmt.setString(2, MName.getText());
            praparedStmt.setInt(3, Integer.valueOf(MPrice.getText()));
            praparedStmt.setInt(4, Integer.valueOf(MQuantity.getText()));
            praparedStmt.setDate(5, ManDate);
            praparedStmt.setDate(6, ExpDate);
            praparedStmt.setString(7, MCompany.getSelectedItem().toString());
            //int row = praparedStmt.executeUpdate();
            praparedStmt.execute();
            JOptionPane.showMessageDialog(null, "ADDED");
            con.close();
            SelectMed();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "not");
        }
        
    }//GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        if(MID.getText().isEmpty() || MName.getText().isEmpty()|| MPrice.getText().isEmpty()|| MQuantity.getText().isEmpty())
        {
            
        }
        else
        {
        try
        {
            java.sql.Date ManDate = new java.sql.Date(MfDate.getDate().getTime());
            java.sql.Date ExpDate = new java.sql.Date(ExDate.getDate().getTime());
            String query = "UPDATE medicine SET MedicineName = ?,Price = ?,Quantity = ?,Mfdate = ?,ExpDate =?,MedCom = ? WHERE MEdicineID =?";
            
            stmt = con.createStatement();
            
            PreparedStatement praparedStmt = con.prepareStatement(query);
            
            
            praparedStmt.setString(1, MName.getText());
            praparedStmt.setInt(2, Integer.valueOf(MPrice.getText()));
            praparedStmt.setInt(3, Integer.valueOf(MQuantity.getText()));
            praparedStmt.setDate(4, ManDate);
            praparedStmt.setDate(5, ExpDate);
            praparedStmt.setString(6, MCompany.getSelectedItem().toString());
            praparedStmt.setInt(7, Integer.valueOf(MID.getText()));
            //int row = praparedStmt.executeUpdate();
            praparedStmt.execute();
            JOptionPane.showMessageDialog(null, "UPDATED");
            con.close();
            SelectMed();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "not UPDATED");
        }
        }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        if(MID.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Enter The Medicine To be Deleted");
        }
        else
        {
            try
            {
                //con = databaseConnection.connection();
                
                stmt = con.createStatement();
     
            
                String MedicineId = MID.getText();
                String query = "DELETE FROM medicine WHERE MedicineID="+MedicineId;
                
                //Statement Add = con.createStatement();
                //Add.executeUpdate(query);
                stmt.executeUpdate(query);
                SelectMed();
                
                JOptionPane.showMessageDialog(this, "Medicine Deleted Successfully");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, "NOT DELETED");
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        MID.setText("");
        MName.setText("");
        MPrice.setText("");
        MQuantity.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void MedicineTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MedicineTableMouseClicked
        DefaultTableModel model = (DefaultTableModel)MedicineTable.getModel();
        int Myindex = MedicineTable.getSelectedRow();
        MID.setText(model.getValueAt(Myindex, 0).toString());
        MName.setText(model.getValueAt(Myindex, 1).toString());
        MPrice.setText(model.getValueAt(Myindex, 2).toString());
        MQuantity.setText(model.getValueAt(Myindex, 3).toString());
    }//GEN-LAST:event_MedicineTableMouseClicked

    private void companylblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companylblMouseClicked
        new company().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_companylblMouseClicked

    private void AgentlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgentlblMouseClicked
        new Agents().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AgentlblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Medicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Agentlbl;
    private com.toedter.calendar.JDateChooser ExDate;
    private javax.swing.JComboBox<String> MCompany;
    private javax.swing.JTextField MID;
    private javax.swing.JTextField MName;
    private javax.swing.JTextField MPrice;
    private javax.swing.JTextField MQuantity;
    private javax.swing.JLabel ManfDate;
    private javax.swing.JLabel MediCom;
    private javax.swing.JLabel MediExpDate;
    private javax.swing.JLabel MediID;
    private javax.swing.JLabel MediName;
    private javax.swing.JLabel MediPrice;
    private javax.swing.JLabel MediQuantity;
    private javax.swing.JTable MedicineTable;
    private com.toedter.calendar.JDateChooser MfDate;
    private javax.swing.JButton add;
    private javax.swing.JButton clear;
    private javax.swing.JLabel companylbl;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
